-- create database
CREATE DATABASE IF NOT EXISTS `authenticator`;
CREATE DATABASE IF NOT EXISTS `test_authenticator`;

CREATE DATABASE IF NOT EXISTS `wallet`;
CREATE DATABASE IF NOT EXISTS `test_wallet`;

CREATE DATABASE IF NOT EXISTS `payment`;
CREATE DATABASE IF NOT EXISTS `test_payment`;
